---
name: Make

on:
  schedule:
    - cron: '0 0 1 * *'
  pull_request:
    branches:
      - master

jobs:
  make:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: |
            mingw-w64-ucrt-x86_64-efl
            mingw-w64-ucrt-x86_64-rust
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-cargo-msrv
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-vala
            mingw-w64-ucrt-x86_64-libsoup3
            mingw-w64-ucrt-x86_64-libgit2-glib
            mingw-w64-ucrt-x86_64-libarchive

      - name: Build on Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          bash -x .github/workflows/main.sh

      - name: Build on Unix
        if: runner.os != 'Windows'
        shell: bash
        run: |
          bash -x .github/workflows/main.sh
